project_id = "hmgxicjynuxsnijhmvth"

[functions.send-enrollment-notification]
verify_jwt = true

[functions.generate-certificate-pdf]
verify_jwt = true

[functions.issue-certificate]
verify_jwt = true
